### ISSUE TITLE
Illegal Memory Access when using Block-Sparse Flash Attention, head_dim=128

### ISSUE THREAD

**Issue by LLLLxmmm** [HazyResearch/flash-attention#169]
Hi, Tri Dao
Thanks for this great work!

I want to use blocksparse flash attention on A100 when head dim=128, I modified the code as follows：
```
void run_fmha_block_fp16_sm80(Launch_params<FMHA_fprop_params> &launch_params,
                             const bool configure) {
    if (launch_params.params.d == 16) {
        using Kernel_traits = FMHA_kernel_traits<256, 16, 16, 1, 4, 0x08u>;
        run_fmha_block_fp16_sm80_loop_<Kernel_traits>(launch_params, configure);
    } else if (launch_params.params.d == 32) {
        using Kernel_traits = FMHA_kernel_traits<256, 32, 16, 1, 4, 0x08u>;
        run_fmha_block_fp16_sm80_loop_<Kernel_traits>(launch_params, configure);
    } else if (launch_params.params.d == 64) {
        using Kernel_traits = FMHA_kernel_traits<256, 64, 16, 1, 4, 0x08u>;
        run_fmha_block_fp16_sm80_loop_<Kernel_traits>(launch_params, configure);
    } else if (launch_params.params.d == 128) {
        using Kernel_traits = FMHA_kernel_traits<128, 128, 16, 1, 4, 0x08u>;
        run_fmha_block_fp16_sm80_loop_<Kernel_traits>(launch_params, configure);
    }
}
```

but encountered some problems：
```
CUDA error (/data_beta_wulan1/lxm/code/blocksparse-flashattn/flash-attention-main/csrc/flash_attn/src/fmha_block_fprop_fp16_kernel.sm80.cu:78): an illegal memory access was encountered
```

I would like to know whether the current block-sparse flash attn supports head dim=128？

**Comment by LLLLxmmm** [comment]
And I am using 1.12.1 for torch and 11.3 for cuda.

**Comment by tridao** [comment]
I don't think it blocksparse FlashAttention supports headdim=128, I've never tested.

**Comment by kuizhiqing** [comment]
> I don't think it blocksparse FlashAttention supports headdim=128, I've never tested.

Thanks again for your reply, I've try to implement the support for hdim=128 case by modifying
the following,
```cpp
diff --git a/csrc/flash_attn/src/fmha_block_dgrad_kernel_1xN_loop.h b/csrc/flash_attn/src/fmha_block_dgrad_kernel_1xN_loop.h
index 9ad4569..1ed692e 100644
--- a/csrc/flash_attn/src/fmha_block_dgrad_kernel_1xN_loop.h
+++ b/csrc/flash_attn/src/fmha_block_dgrad_kernel_1xN_loop.h
@@ -49,7 +49,7 @@ inline __device__ void compute_block_dq_dk_dv_1xN_one_iter(const Params &params,
         fmha::Cta_tile_extd<Cta_tile_p::N, Cta_tile_p::K, Cta_tile_p::M, Cta_tile_p::WARPS_N, 1, Cta_tile_p::WARPS_M>;
 
     static_assert(Cta_tile_dkv::M == 512 ||  Cta_tile_dkv::M == 256 || Cta_tile_dkv::M == 128);
-    static_assert(Cta_tile_dkv::N == 16 || Cta_tile_dkv::N == 32 || Cta_tile_dkv::N == 64);
+    static_assert(Cta_tile_dkv::N == 16 || Cta_tile_dkv::N == 32 || Cta_tile_dkv::N == 64 || Cta_tile_dkv::N == 128);
     static_assert(Cta_tile_dkv::K == 16);
 
     // The MMA tile for the 1st GEMM.
diff --git a/csrc/flash_attn/src/fmha_block_dgrad_kernel_loop.sm80.cu b/csrc/flash_attn/src/fmha_block_dgrad_kernel_loop.sm80.cu
index b33880f..410b944 100644
--- a/csrc/flash_attn/src/fmha_block_dgrad_kernel_loop.sm80.cu
+++ b/csrc/flash_attn/src/fmha_block_dgrad_kernel_loop.sm80.cu
@@ -61,6 +61,9 @@ void run_fmha_block_dgrad_sm80(const FMHA_dgrad_params &params, cudaStream_t str
         } else if (params.d == 64) {
             using Kernel_traits = FMHA_kernel_traits<256, 64, 16, 1, 8, 0x100u, elem_type>;
             run_fmha_block_dgrad_sm80_loop_<Kernel_traits>(params, stream);
+        } else if (params.d == 128) {
+            using Kernel_traits = FMHA_kernel_traits<256, 128, 16, 1, 8, 0x08u, elem_type>;
+            run_fmha_block_dgrad_sm80_loop_<Kernel_traits>(params, stream);
         }
     }));
 }
diff --git a/csrc/flash_attn/src/fmha_block_fprop_kernel.sm80.cu b/csrc/flash_attn/src/fmha_block_fprop_kernel.sm80.cu
index 01e1d32..0adc617 100644
--- a/csrc/flash_attn/src/fmha_block_fprop_kernel.sm80.cu
+++ b/csrc/flash_attn/src/fmha_block_fprop_kernel.sm80.cu
@@ -88,6 +88,9 @@ void run_fmha_block_sm80(Launch_params<FMHA_fprop_params> &launch_params,
         } else if (launch_params.params.d == 64) {
             using Kernel_traits = FMHA_kernel_traits<256, 64, 16, 1, 4, 0x08u, elem_type>;
             run_fmha_block_sm80_loop_<Kernel_traits>(launch_params, configure);
+        } else if (launch_params.params.d == 128) {
+            using Kernel_traits = FMHA_kernel_traits<256, 128, 16, 1, 4, 0x08u, elem_type>;
+            run_fmha_block_sm80_loop_<Kernel_traits>(launch_params, configure);
         }
     }));
 }
```

While I can run it and the forward seems OK but the backward seems broken somewhere,
```
Forward
Mismatched elements: 31203 / 3145728 (0.992%)
Max absolute difference: 0.0004883
Max relative difference: 0.000977

Backward
Mismatched elements: 1699913 / 3145728 (54%)
Max absolute difference: 1.387
Max relative difference: 9.875
```

Can you possibly give me some help or some clue to handle it ?

Thank you in advance.

BTW, I'm trying to implement sparse version with bf16 and hdim=128, I'd like to make a pull request after this problem solved if you'er OK.

**Comment by kuizhiqing** [comment]
Please refer to https://github.com/HazyResearch/flash-attention/pull/254 if you are looking for block sparse implementation.
