### ISSUE TITLE
Illegal Memory Access when number of keys != queries

### ISSUE THREAD

**Issue by calclavia** [HazyResearch/flash-attention#20]
I'm experimenting with a scenario where I have more keys than queries (e.g., a common scenario during inference where the prior keys/values are cached). When trying to use different query and keys, I get:

```
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

This only happens during the backward pass. I can run the forward pass and it won't crash.
Seems like it's related to FlashAttention indexing something that is out of bounds?

```
  File "/workspace/models/attention.py", line 176, in flash_attention
    causal=True
  File "/opt/conda/lib/python3.7/site-packages/flash_attn-0.1-py3.7-linux-x86_64.egg/flash_attn/flash_attn_interface.py", line 243, in flash_attn_unpadded_func
    dropout_p, softmax_scale, causal, return_attn_probs)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352464346/work/torch/csrc/autograd/python_anomaly_mode.cpp:102.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
Error executing job with overrides: ['name=test-tx-persist', '+experiment=tx']
```

Note: In my scenario, all batches have the same sequence length. I set cu seqlens q and k as the cumsum of `[0]+[q_seq_len] * b` and cumsum of  `[0]+[k_sq] * b` respectively.

If I set both keys and queries to have the same sequence length, then everything works.

**Comment by tridao** [comment]
Thanks for trying our code and for the bug report!

I'm trying to reproduce the issue. From my quick test below it was fine when there are more keys than queries.
Perhaps your use case is different? What shapes are the q, k, v? Which GPU and CUDA version are you using?
A short script that reproduces the issue would be very helpful.

Here's my script that ran fine:
```
import torch

from flash_attn.flash_attn_interface import flash_attn_unpadded_func


torch.manual_seed(0)
batch_size = 32
seqlen_q = 97
seqlen_k = 573
nheads = 16
d = 64
dropout_p = 0.1
causal = True
dtype = torch.float16
device = 'cuda'

q = torch.randn(batch_size * seqlen_q, nheads, d, dtype=dtype, device=device, requires_grad=True)
k = torch.randn(batch_size * seqlen_k, nheads, d, dtype=dtype, device=device, requires_grad=True)
v = torch.randn(batch_size * seqlen_k, nheads, d, dtype=dtype, device=device, requires_grad=True)

cu_seqlens_q = torch.arange(0, seqlen_q * (batch_size + 1), step=seqlen_q, device=device, dtype=torch.int32)
cu_seqlens_k = torch.arange(0, seqlen_k * (batch_size + 1), step=seqlen_k, device=device, dtype=torch.int32)

out = flash_attn_unpadded_func(q, k, v, cu_seqlens_q, cu_seqlens_k, seqlen_q, seqlen_k,
                               dropout_p, causal=causal)
print(out.mean().item())  # To synchronize CUDA
g = torch.randn_like(out)
out.backward(g)
print(q.grad.mean().item(), k.grad.mean().item(), v.grad.mean().item())  # To synchronize CUDA
```

**Comment by tridao** [comment]
Were you using head dimension = 16?
There was a bug in the forward pass with headdim = 16 that I just fixed, which may or may not be related. 
Can you try again with the latest commit?

**Comment by calclavia** [comment]
@tridao I wasn't using head dim = 16. For my implementation, I setup the cu_seqlens as such:
```
cu_seqlens_q = torch.tensor(
                [0]+[q_sq] * b, dtype=torch.int32, device=query_layer.device).cumsum(dim=-1).to(torch.int32)
cu_seqlens_k = torch.tensor(
                [0]+[k_sq] * b, dtype=torch.int32, device=query_layer.device).cumsum(dim=-1).to(torch.int32)
```
which seems to lead to that error. However, when I change my implementation to use torch.arange as your example, I no longer have the error. It seems to be working now.

**Comment by calclavia** [comment]
@tridao Although it no longer crashes, for the example you showed, how would I specify the starting position for the query to attend to? For example:

I have a causal attention setup with 1 query and 10 keys. Does this mean the query will attend to all keys, or just the first key because it's causal? How can I specify which keys are "before" or "after" the first query?

**Comment by lucidrains** [comment]
@calclavia :wave:  Hey Henry, fancy seeing you here!

![x3](https://user-images.githubusercontent.com/108653/178149477-db1d461b-6ef0-4ce3-8169-ed6ca7ff4dfe.png)

what you are looking for is the causal with prefix attention mask. it shows up not only for your edge case but also for transformer-xl memories too

it would require that flash attention can take the full attention matrix. the alternative memory efficient version is to accept the indices of the queries and keys, and it does some comparison logic on the fly to determine the boolean at the `q_i, k_j` coordinate

```python
seq_dim = -2
i = q.shape[seq_dim]
j = k.shape[seq_dim]
attn_mask = torch.ones((i, j), dtype = torch.bool).triu(j - i + 1)

flash_attention(q, k, v, attn_mask = attn_mask)
```

**Comment by lucidrains** [comment]
@calclavia are you seeing stable training results using flash attention so far?

**Comment by calclavia** [comment]
@lucidrains Yep, my training curves seem to match that of regular attention on preliminary tests on enwiki8.

Thanks for putting up that picture as it helps illustrate my causal + prefix case. I think having to supply a full attention-mask would be more general than supporting causal with the prefix, but causal with prefix should probably be the default scenario when num keys != num queries. Otherwise, it would be equivalent to computing attention with the final few keys trimmed off.

**Comment by lucidrains** [comment]
@calclavia that's great to hear re: stability!

yes i agree, i'm just thinking ahead, when Tri implements relative positions, he'll have enough information to also do the causal masking

**Comment by lucidrains** [comment]
yea, autogenerated causal mask with support for prefix would definitely make flash attention more widely used

as an example, the recent [Perceiver AR paper](https://arxiv.org/abs/2202.07765) uses this on the first layer

**Comment by lucidrains** [comment]
ok, im getting excited about flash attention again

if it turns out to be the real deal, i may take a trip to the south bay and wine and dine Tri and his team haha

**Comment by tridao** [comment]
> @tridao Although it no longer crashes, for the example you showed, how would I specify the starting position for the query to attend to? For example:
> 
> I have a causal attention setup with 1 query and 10 keys. Does this mean the query will attend to all keys, or just the first key because it's causal? How can I specify which keys are "before" or "after" the first query?
> 
> Another example: If I have 2 queries and 10 keys. If it's a causal setup, does this mean the 1st query will attend to the first 9 keys, and the 2nd query will attend to all 10 keys? This is the typical scenario for causal attention inference. When I tested your example with 1 query and 2 keys, it doesn't seem to exhibit the above expected behavior.
> 
> Some clarification on the docs for this would be great!

Right now `causal` means query `i` will attention to key `1, 2, ..., i`. I'm thinking mainly of training auto-regressive LM, where `seqlen_q == seqlen_k`.
I'm not too sure what `causal` should mean when `seqlen_q != seqlen_k`.
Right now, if there are 2 queries and 10 keys, then query 1 will attend to key 1 and query 2 will attend to key 1 & 2.

I'm open to suggestions here (what causal should mean if `seqlen_q != seqlen_k`). It's all just simple index calculation in CUDA so it'll be pretty easy to change.

Eventually I want to support full N x N attention bias / mask, but that will probably be slightly less efficient since we need to read in an N x N matrix.

**Comment by lucidrains** [comment]
So the efficient way would be to generate the time indices of queries and keys and then compute key times > query times for what to mask out (past cannot attend to future)

For prefix causal, query times would range from 0 to query length, while key times would range from (query length - key length) to query length

I think eventually you will have to support NxN bias and mask though, for ultimate flexibility. As an example, alphafold2 projects their pairwise representations and biases their single representation's attention matrix https://github.com/lucidrains/alphafold2/blob/main/alphafold2_pytorch/alphafold2.py#L252

There are also a myriad of different pretraining schemes out there for transformers with their own fancy attention masking schemes

**Comment by lucidrains** [comment]
Perhaps for starters you can use the strategy above, as it also generalizes to the base causal mask

Then allow for query and key times to be overridden

But I'm far from a cuda expert, so whatever you think is best

**Comment by lucidrains** [comment]
you can't go wrong just supporting prefix causal masking when causality is turned on and query length is not equal to key length

there are just numerous architectures that depend on this, transformer-xl among them

**Comment by lucidrains** [comment]
clearer in code

```python
import torch

q = torch.randn(1, 1024, 512)
k = torch.randn(1, 2048, 512)

i = q.shape[-2]
j = k.shape[-2]

q_times = torch.arange(i)
k_times = torch.arange(i - j, i)

# within the kernel

k_index = 2047 # accessible within the loop
q_index = 512  # accessible within the loop

should_mask_to_neg_inf = k_times[k_index] > q_times[q_index] 

assert should_mask_to_neg_inf

assert torch.all(
    (q_times[:, None] < k_times[None, :]) == torch.ones((i, j), dtype = torch.bool).triu(j - i + 1)
)
```

**Comment by lucidrains** [comment]
yea, as long as you support prefix causal, base causal, and NxN attention masking / biasing, that's 95% of the use cases out there

**Comment by calclavia** [comment]
> ```python
> flash_attention
> ```

I'm looking at the flash_attention_interface and it doesn't seem like there's a way to pass in a custom mask right now. As @tridao hinted, this is probably a future work.

**I have a simple proposal re: @tridao** 

As to how causal should behave when num keys != num queries, my thought is that the current behavior probably has no use case:

> Right now, if there are 2 queries and 10 keys, then query 1 will attend to key 1 and query 2 will attend to key 1 & 2.

This is equivalent to just slicing out the last 8 keys and doing non-prefix causal attention. If the user's intention is to do this, they could pre-slice the qkv inputs to achieve this effect. I think the right behavior should be:

_If there are 2 queries and 10 keys, then query 1 will attend to key 1 to 9 and query 2 will attend to key 1 to 10 (all keys)._

This is causal attention with prefix and is shown in the image by @lucidrains. @lucidrains 's proposed idea with passing time indices seems more general but I personally don't see a use case where you need this. You can always achieve the equivalent via slicing the key tensor prior to passing it to flash attention since, effectively, some of the tail keys will never be attended to anyway. <- Perhaps I'm missing some use cases where passing time indices would be helpful and cannot be achieved via preparing the input.

**Comment by lucidrains** [comment]
@calclavia yea i agree

in which case just passing in the difference between the lengths of the queries and keys is sufficient. this would fix the inference causal attention + cache, transformer-xl like memories, as well as the new perceiver AR attention + some other brain works

**Comment by lucidrains** [comment]
i think NxN (mask or bias) should be offered though, as it is the most general case, even if not efficient

**Comment by lucidrains** [comment]
haha, it is sometimes surprising to me how a simple equation like attention can be so complex in practice

**Comment by calclavia** [comment]
@tridao Is the adjustment from our suggested causal implementation a difficult change in the CUDA/C code?

**Comment by jesus-andres-ferrer** [comment]
Hi, 
First of all I would like to congratulate the for this neat work. I am having a lot of fun going through the code and understanding it. 


> Right now `causal` means query `i` will attend to key `1, 2, ..., i`. I'm thinking mainly of training auto-regressive LM, where `seqlen_q == seqlen_k`. I'm not too sure what `causal` should mean when `seqlen_q != seqlen_k`. Right now, if there are 2 queries and 10 keys, then query 1 will attend to key 1 and query 2 will attend to key 1 & 2.
> 
> I'm open to suggestions here (what causal should mean if `seqlen_q != seqlen_k`). It's all just simple index calculation in CUDA so it'll be pretty easy to change.

When is_causal=True and  seqlen_q < seqlen_k  (not sure what to do in the opposite case seqlen_q > seqlen_k ), I would have expected personally the opposite behaviour, that is if `causal' that should mean query `i' can attend to keys `seqlen_k - i, ..., seqlen_k-2, seqlen_k-1'. This will simulate autoregressive with prefix and will be more useful than '1, 2, ..., i', which essentially means that seqlen_k - seqlen_q is ignored, if I understand properly and apologies if misunderstood in my sie. 

I think this will automatically cover some of the cases above ? 
Maybe a templated functor can be provided to the kernels to index left, rightmost or other patterns that would/could help other efficient user cases ? 

Thank you very much,

**Comment by tridao** [comment]
Ya that makes sense. I'll try to get to it this weekend (been busy with preparing for ICML talks etc.)

**Comment by lucidrains** [comment]
> 

if you did it this way, you would simply remove the `k_len - q_len` keys that are omitted from attention altogether

**Comment by jesus-andres-ferrer** [comment]
Hi, 
I think we intended to say the same, maybe I failed to specify the idea on the indexes above, now not sure I understand the indexing you are using.
I think it is more clear in the code for me: 
`
    begin = Is_causal ? std::max(begin, loop_step_idx * Cta_tile_p::N / Cta_tile_p::M) : begin;
` 
this IIUC, should be: 
`
    begin =  begin;
`
and the end should be modified so that the causal mask should be applied to the rightmost square (as given by q_len) elements of K while we can attend to the leftmost rectangle prefix (that shouldn't be zeroed out). That only makes sense quen q_len < k_len or when q_len > k_len. I agree specification above is incorrect. In both cases, it won't make sense to pass the delta columns from k and v, independently of whether we focus on the letmos square to apply self-attention on the rightmost.


Apologies for the missspecification,

**Comment by lucidrains** [comment]
@jesus-andres-ferrer ah no problem, yes, I think both Henry and I are referring to the first configuration!

```
1 1 1 1 1 1 1 0 0 0 0
1 1 1 1 1 1 1 1 0 0 0
1 1 1 1 1 1 1 1 1 0 0
1 1 1 1 1 1 1 1 1 1 0
1 1 1 1 1 1 1 1 1 1 1
```

we are all on the same page then

**Comment by lucidrains** [comment]
just realized sometimes you see

```
1 1 1 1 1 1 1 0 0 0 0
0 1 1 1 1 1 1 1 0 0 0
0 0 1 1 1 1 1 1 1 0 0
0 0 0 1 1 1 1 1 1 1 0
0 0 0 0 1 1 1 1 1 1 1
```

for local attention with fixed window size

**Comment by lxuechen** [comment]
Hi all,

Thanks for the discussions on this topic. Reading the thread and the PR to the OpenProteinAI codebase, it seems the backward pass for the causal with prefix attention isn't finished yet. Would @timt51 @tridao be able to share the timeline on this? 

I'm interested in using flashattention for **training/fine-tuning** T5-style models, and the encoder-decoder setup necessitates this type of masking. I haven't thought deeply whether there'd be another way around it, but would love to hear suggestions if anyone has thought about this!
