### ISSUE TITLE
LayerNorm backward kernel's random behaviour leads to allocation error

### ISSUE THREAD

**Issue by zhouyizhuang-megvii** [HazyResearch/flash-attention#74]
### Problem
I am benchmarking a ViT using flash_attn, and turn on `fused_dropout_add_ln = True`. The forward pass is okay, however, it raises at the "first" layernorm during the backward pass.
```
from flash_attn.models.vit import vit_base_patch16_224

@register_model
def flash_vit_base_patch16_224(pretrained=False, **kwargs):
    kwargs["use_flash_attn"] = True
    kwargs["fused_bias_fc"] = True
    kwargs["fused_dropout_add_ln"] = True
    return vit_base_patch16_224(pretrained, **kwargs)
```

The traceback is as follows, **it differs every time**, either showing cuda out of memory, or allocation a tensor of negative shape.
```
Traceback (most recent call last):
  File "benchmark.py", line 676, in <module>
    main()
  File "benchmark.py", line 660, in main
    results = benchmark(args)
  File "benchmark.py", line 592, in benchmark
    run_results = _try_run(
  File "benchmark.py", line 541, in _try_run
    raise e
  File "benchmark.py", line 538, in _try_run
    results = bench.run()
  File "benchmark.py", line 419, in run
    _step()
  File "benchmark.py", line 398, in _step
    self.loss(output, target).backward()
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/autograd/function.py", line 267, in apply
    return user_fn(self, *args)
  File "/home/xxx/flash-attention/flash_attn/ops/layer_norm.py", line 125, in backward
    dx0mat, dx1mat, dgamma, dbeta = _dropout_add_layer_norm_prenorm_backward(
  File "/home/xxx/flash-attention/flash_attn/ops/layer_norm.py", line 50, in _dropout_add_layer_norm_prenorm_backward
    dx0mat, dx1mat, dgamma, dbeta, _, _ = dropout_layer_norm.dropout_add_ln_prenorm_bwd(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1696.02 GiB (GPU 0; 10.76 GiB total capacity; 3.85 GiB already allocated; 5.77 GiB free; 3.94 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
and
```
  ... ...
  File "/home/zhouyizhuang/flash-attention/flash_attn/ops/layer_norm.py", line 125, in backward
    dx0mat, dx1mat, dgamma, dbeta = _dropout_add_layer_norm_prenorm_backward(
  File "/home/zhouyizhuang/flash-attention/flash_attn/ops/layer_norm.py", line 50, in _dropout_add_layer_norm_prenorm_backward
    dx0mat, dx1mat, dgamma, dbeta, _, _ = dropout_layer_norm.dropout_add_ln_prenorm_bwd(
RuntimeError: Trying to create tensor with negative dimension -1381864448: [-1381864448, 768]
```

### Try to figure it out
I dive into the kernels and find where tensor allocates:

https://github.com/HazyResearch/flash-attention/blob/b0ed0a73fdf1b905af84a5e4561201b773ee625c/csrc/layer_norm/ln_api.cpp#L415-L416

and where their first dim `launch_params.params.ctas_per_col` initialized:

https://github.com/HazyResearch/flash-attention/blob/b0ed0a73fdf1b905af84a5e4561201b773ee625c/csrc/layer_norm/ln_bwd_semi_cuda_kernel.cu#L46-L49

I print out the values:

```c++
printf("launch_params.params.ctas_per_col = %d, %d * %d / %d\n",
    launch_params.params.ctas_per_col,
    launch_params.props->multiProcessorCount,
    ctas_per_sm,
    Kernel_traits::CTAS_PER_ROW);
```

and find everything's fine during forward, but backward we get a weird `ctas_per_sm`:

```
## this is forward
launch_params.params.ctas_per_col = -68, 68 * -1 / 1
## this is backward
launch_params.params.ctas_per_col = 592800768, 68 * -433411328 / 1
```

The `ctas_per_sm` seems to remain **uninitialized** every time after `cudaOccupancyMaxActiveBlocksPerMultiprocessor` calls.

The forward and backward code seems all the same except for `Kernel_traits::SMEM_BYTES_FWD` for forward and  `Kernel_traits::SMEM_BYTES` for backward.

I don't know why, and work-around it by setting `ctas_per_sm` to a constant value.

### Environment
* ubuntu 20.04
* torch==1.13.0(cuda 11.7)
* local cuda 11.8 for compiling layernorm kernels
* device: 2080ti

**Comment by tridao** [comment]
Thanks for the report.
I don't know what's wrong but it's likely the GPU type (I've tested on A100). I've added a check on the return value of `ctas_per_sm`.

The dropout_layer_norm kernel officially only supports Ampere architecture (I haven't had time to test on other GPUs). In fact the `setup.py` only compiles for sm80. Did you do anything to get it to compile for Turing?

**Comment by tridao** [comment]
Can you print out `Kernel_traits::SMEM_BYTES_FWD` and `Kernel_traits::SMEM_BYTES`? It's possible that it requires more shared memory (SRAM) than what Turing has.

Does Apex's FastLayerNorm work for you (for the same dimension)?

**Comment by zhouyizhuang-megvii** [comment]
Thank you very much for your reply!

> In fact the setup.py only compiles for sm80. Did you do anything to get it to compile for Turing?

Well I didn't notice that. So despite that it has been compiled for sm80, it still runs on an sm75 2080ti (but I didn't check the numerical results).

> Can you print out Kernel_traits::SMEM_BYTES_FWD and Kernel_traits::SMEM_BYTES?

`Kernel_traits::SMEM_BYTES_FWD` is 0, and `Kernel_traits::SMEM_BYTES` is 12288 (= 768 width * 16?)

### Compile for sm75, and problem solved

I re-compile the layernorm kernels for sm75 2080ti, **and it works**!

it shows when forward
```
launch_params.params.ctas_per_col = 544, 68 * 8 / 1, Kernel_traits::SMEM_BYTES_FWD = 0
```

and backward
```
launch_params.params.ctas_per_col = 204, 68 * 3 / 1, Kernel_traits::SMEM_BYTES = 12288
```

so the kernel traits are the same, but the `ctas_per_sm` is different compared to sm80. To summary, I think it's due to `cudaOccupancyMaxActiveBlocksPerMultiprocessor`'s different behaviour on different gpu architectures.

**Comment by tridao** [comment]
It's strange that the layernorm forward pass even ran even though it wasn't even compiled for Turing :D
In any case I've added sm_70 to the setup.py file so the layernorm extension should work for Turing (and Volta) now.
